spring:
  application:
    name: inventory-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/inventory_db}
    username: ${SPRING_DATASOURCE_USERNAME:simranjeetkaur}
    password: ${SPRING_DATASOURCE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info